AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Web Search Lambda Tool for Financial Research Agent
  
  This SAM template deploys a Lambda function that provides web search
  capabilities using the Tavily API, designed to be used with Amazon
  Bedrock Agents for financial research tasks.

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.11

Parameters:
  TavilyApiKey:
    Type: String
    Description: Your Tavily API key for web search
    NoEcho: true

Resources:
  # The main Lambda function for web search
  WebSearchFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: web_search
      Description: Searches the web for financial news and information using Tavily API
      Handler: lambda_function.lambda_handler
      CodeUri: .
      Environment:
        Variables:
          TAVILY_API_KEY: !Ref TavilyApiKey
      Policies:
        # Basic Lambda execution permissions
        - AWSLambdaBasicExecutionRole
        # Optional: Add Secrets Manager access if storing API key there
        # - SecretsManagerReadWrite
      Tags:
        Project: financial-research-agent
        Component: web-search-tool

  # Permission for Bedrock to invoke this Lambda
  BedrockInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref WebSearchFunction
      Action: lambda:InvokeFunction
      Principal: bedrock.amazonaws.com
      SourceAccount: !Ref AWS::AccountId

  # CloudWatch Log Group with retention policy
  WebSearchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${WebSearchFunction}"
      RetentionInDays: 14

Outputs:
  WebSearchFunctionArn:
    Description: ARN of the web search Lambda function (use this in your agent configuration)
    Value: !GetAtt WebSearchFunction.Arn
    Export:
      Name: WebSearchFunctionArn
      
  WebSearchFunctionName:
    Description: Name of the web search Lambda function
    Value: !Ref WebSearchFunction
